parameters:  
- name: buildConfiguration
  displayName: Build Configuration
  type: string
  default: Debug
  values:
  - Debug
  - Release

# manual run only
trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'app/AzureWorld/TotallyNotMarioWorld/TotallyNotMarioWorld.csproj'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: $(solution)
 
- task: VSBuild@1 
  inputs: 
    solution: $(solution)
    platform: $(buildPlatform)
    configuration: ${{ parameters.buildConfiguration }}
 
- powershell: |
    $path = "$(Build.SourcesDirectory)"
    $platform = "$(buildPlatform)"
    $buildConfig = "${{ parameters.buildConfiguration }}"
 
    & "$path\app\AzureWorld\TotallyNotMarioWorld\bin\$platform\$buildConfig\net6.0\TotallyNotMarioWorld.exe"
  displayName: Run Application